git:
  depth: 3

language: objective-c
sudo: required
osx_image: xcode10.2.1

before_install:
  - bundle install
  - pod install --repo-update

env:
  global:
    - IOS_SDK="iphonesimulator12.2"
    - FRAMEWORK="Flix"
  matrix:
    - SDK="$IOS_SDK"      TEST=0  DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=12.2"

notifications:
  email: false

install: true

env:
  - BUILD="xcodebuild -workspace Flix.xcworkspace -scheme Example -configuration Release -destination 'platform=iOS Simulator,name=iPhone 8' build | xcpretty"
  - BUILD="xcodebuild test -workspace Flix.xcworkspace -scheme Flix -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 8' build | xcpretty"
  - BUILD="pod lib lint Flix.podspec --verbose --allow-warnings"

script: eval "${BUILD}"

after_success:
  - sleep 5 # workaround https://github.com/travis-ci/travis-ci/issues/4725
