git:
  depth: 3

os: osx
language: objective-c
sudo: true
osx_image: xcode11.3

before_install:
  - bundle install
  - bundle exec pod install

notifications:
  email: false

install: true

env:
  - BUILD="xcodebuild -workspace Flix.xcworkspace -scheme Example -configuration Release -destination 'platform=iOS Simulator,name=iPhone 11' build | xcpretty"
  - BUILD="xcodebuild test -workspace Flix.xcworkspace -scheme Flix -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 11' build | xcpretty"
  - BUILD="bundle exec pod lib lint Flix.podspec --verbose"

script: eval "${BUILD}"

after_success:
  - sleep 5 # workaround https://github.com/travis-ci/travis-ci/issues/4725
